services:
  backend:
    image: nainani344sumit/go_lookauth:v1
    container_name: go_lookauth
    depends_on:
      - redis
      - mongo
    env_file:
      - .env
    ports:
      - "8080:8080"

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisV:/data

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongoV:/data/db

volumes:
  redisV:  
  mongoV:  
